
PUT http://condemned.local/api/points/updateAll HTTP/1.1
content-type: application/json
Authorization: Bearer 61|OTNXivRbM0NrNF2JpN7hixX6W3vmDA94Da26z2aK

{"points":[
    {"id":2,"updated_at":"2022-08-15T08:57:53.322","freedom_id":2,"startdate":"2022-03-08 00:00:00","enddate":"2022-03-08 00:30:00","node_id":7,"status":2,"info":"null"}
    ,
    {"id":3,"updated_at":"2022-08-15T08:57:53.322","freedom_id":2,"startdate":"2022-03-08 00:00:00","enddate":"2022-03-08 00:30:00","node_id":7,"status":4,"info":"null"}    
    ,
    {"id":27,"updated_at":"2022-08-15T08:57:53.322","freedom_id":2,"startdate":"2022-03-08 00:00:00","enddate":"2022-03-08 00:30:00","node_id":7,"status":32,"info":"null"}
    ]
}
